extends SceneTree
## CAN THIS PROJECT BE BUILT, AND IS IT ABOUT TO LEAK A KEYSTORE?
##
##   godot --headless --path . --script res://tests/test_export.gd
##
## `export_presets.cfg` is normally generated by the editor and never read by
## anything again. There is no editor in this loop — it was written by hand on
## 15 Sep 2026 — and it is the only file in the project whose mistakes are
## invisible until somebody tries to ship.
##
## Three kinds of question here, and they are different kinds:
##
##   * DOES IT PARSE, and are the presets the ones the project claims to have.
##   * DOES IT AGREE WITH `project.godot` — the icon it points at, the
##     orientation, the renderer. A preset that disagrees with the project is a
##     build that behaves differently from the thing that was tested.
##   * IS IT SAFE TO COMMIT. This file is tracked on purpose, which is only
##     defensible while it carries no credential.
##
## WHAT THIS CANNOT DO is run an export — that needs the 1.2GB template set,
## which is not in the repo and should not be. The Linux export WAS run by hand
## on 15 Sep and the binary was launched; see docs/EXPORTING.md.

const PRESETS := "res://export_presets.cfg"

## The fields that must never arrive in git with a value in them.
const SECRETS: Array[String] = [
	"keystore/debug",
	"keystore/debug_password",
	"keystore/debug_user",
	"keystore/release",
	"keystore/release_password",
	"keystore/release_user",
	"apple_team_id",
	"application/signature",
	"codesign/identity",
	"codesign/password",
	"ssh_remote_deploy/extra_args_ssh",
]

var failures: Array[String] = []
var checks: int = 0
var notes: Array[String] = []


func _initialize() -> void:
	print("\n=== 8-Bit Buhurt — can it be built ===\n")
	_test_the_presets_parse()
	_test_the_presets_agree_with_the_project()
	_test_nothing_in_here_is_a_secret()
	_test_the_pack_leaves_the_workshop_behind()
	print("")
	for n in notes:
		print("   " + n)
	print("")
	if failures.is_empty():
		print("THE BUILD HOLDS (%d checks)\n" % checks)
		quit(0)
	else:
		for f in failures:
			print("FAIL: " + f)
		print("\n%d FAILED\n" % failures.size())
		quit(1)


func _ok(cond: bool, label: String, detail: String) -> void:
	checks += 1
	print("  %s  %s — %s" % ["pass" if cond else "FAIL", label, detail])
	if not cond:
		failures.append("%s: %s" % [label, detail])


func _cfg() -> ConfigFile:
	var c := ConfigFile.new()
	if c.load(PRESETS) != OK:
		return null
	return c


## Every `[preset.N]` section, by name.
func _by_name() -> Dictionary:
	var out := {}
	var c := _cfg()
	if c == null:
		return out
	for sec in c.get_sections():
		if sec.ends_with(".options") or not sec.begins_with("preset."):
			continue
		out[String(c.get_value(sec, "name", ""))] = sec
	return out


func _test_the_presets_parse() -> void:
	_ok(FileAccess.file_exists(PRESETS), "there is an export_presets.cfg at all",
		"the project had none until 15 Sep 2026, so nothing could be built")
	var c := _cfg()
	_ok(c != null, "and it parses as a ConfigFile",
		"a malformed preset file fails at ship time and nowhere else")
	if c == null:
		return
	var names := _by_name().keys()
	names.sort()
	## ANDROID IS THE ONE THAT MATTERS and the other two are how you find out
	## something is broken without a phone in your hand.
	_ok(names.has("Android") and names.has("Linux") and names.has("Windows Desktop"),
		"the three presets the project ships are present",
		", ".join(names))
	notes.append("the presets: %s" % ", ".join(names))


func _test_the_presets_agree_with_the_project() -> void:
	var c := _cfg()
	if c == null:
		return
	## THE ICON. `project.godot` has pointed at `res://icon.svg` since the day
	## the project was made and the file was not there — every export would have
	## failed on it, which is a thing nobody could discover without exporting.
	var icon := String(ProjectSettings.get_setting("application/config/icon", ""))
	_ok(icon != "" and ResourceLoader.exists(icon),
		"the icon the project points at exists",
		"%s%s" % [icon, "" if ResourceLoader.exists(icon) else " — MISSING"])

	## THE ORIENTATION, which has no key in the Android preset: Godot writes
	## `android:screenOrientation` into the manifest from this project setting
	## alone. It was 1 — PORTRAIT — under a 960x540 landscape game until the
	## mobile pass, so it is held here rather than trusted.
	var o := int(ProjectSettings.get_setting("display/window/handheld/orientation", -1))
	var landscape: Array[int] = [
		DisplayServer.SCREEN_LANDSCAPE,
		DisplayServer.SCREEN_REVERSE_LANDSCAPE,
		DisplayServer.SCREEN_SENSOR_LANDSCAPE,
	]
	_ok(landscape.has(o), "the handheld orientation is a landscape one",
		"orientation=%d (landscape are %s)" % [o, str(landscape)])

	## AND THE PACKAGE NAME IS A REAL ONE. Godot's default is
	## `com.example.$genname`, which Google Play refuses outright — and refuses
	## at upload, after the build, which is the most expensive moment to find out.
	var android: String = String(_by_name().get("Android", ""))
	var pkg := ""
	if android != "":
		pkg = String(c.get_value(android + ".options", "package/unique_name", ""))
	_ok(pkg != "" and not pkg.begins_with("com.example"),
		"the Android package name is not the placeholder",
		pkg if pkg != "" else "(unset)")
	notes.append("the package: %s, orientation %d, icon %s" % [pkg, o, icon])


func _test_nothing_in_here_is_a_secret() -> void:
	var c := _cfg()
	if c == null:
		return
	var filled: Array[String] = []
	for sec in c.get_sections():
		for key in SECRETS:
			var v := String(c.get_value(sec, key, ""))
			if v.strip_edges() != "":
				filled.append("%s/%s" % [sec, key])
	## THE FILE IS TRACKED IN GIT, which is the opposite of the usual advice and
	## is only defensible while this check passes. A keystore password reaching
	## a repo is the one mistake here that cannot be undone by a later commit.
	_ok(filled.is_empty(), "no credential field has a value in it",
		"%d fields watched%s" % [SECRETS.size(),
			"" if filled.is_empty() else " — FILLED: " + "; ".join(filled)])


func _test_the_pack_leaves_the_workshop_behind() -> void:
	var c := _cfg()
	if c == null:
		return
	## THE AUDITION FOLDER IS 20 OF THE PROJECT'S 25 MEGABYTES OF AUDIO and not
	## one file in it is referenced by the game. Shipping it would roughly double
	## the download for nothing — and `shots/`, `tools/`, `tests/` and `docs/`
	## are the same argument in miniature.
	var want := ["audio/_candidates", "shots", "tools", "tests", "docs"]
	var missing: Array[String] = []
	var seen := 0
	for sec in c.get_sections():
		if sec.ends_with(".options") or not sec.begins_with("preset."):
			continue
		seen += 1
		var ex := String(c.get_value(sec, "exclude_filter", ""))
		for w in want:
			if ex.find(w) < 0:
				missing.append("%s is missing %s" % [String(c.get_value(sec, "name", sec)), w])
	_ok(missing.is_empty(), "every preset leaves the workshop out of the pack",
		"%d presets, %d folders each%s" % [seen, want.size(),
			"" if missing.is_empty() else " — " + "; ".join(missing)])
