#!/usr/bin/env python3
"""
Retro Buhurt — the music set.  One melody, arranged four ways.

WHY THIS IS A SYNTHESISER AND NOT A SOUNDFONT
---------------------------------------------
The event-music recipe renders MIDI through FluidR3_GM, which is right for the
acoustic and metal sets it was written for.  It is wrong here.  Pete asked for
Retro Bowl's idiom with medieval flavour, escalating to "8-bit war drum and
8-bit metal" — and *8-bit* is not a texture you can approximate with a General
MIDI patch.  It is four specific voices:

    PULSE 1/2   square waves at 12.5 / 25 / 50 % duty.  Leads and harmony.
    TRIANGLE    a stepped triangle.  The NES bass, and it cannot be silenced
                cleanly, which is why NES basslines run constantly.
    NOISE       a pseudo-random bit generator.  Every drum on the console.

So those four are written directly.  "8-bit metal" then stops being a metaphor
and becomes the actual technique: a distorted power chord is faked on the NES by
ARPEGGIATING the chord faster than the ear separates it — root, fifth, octave at
60 Hz — which is what makes Mega Man and Castlevania sound like guitars.  And
"war drums" are the noise channel at a long period, doubled by a pitch-dropped
triangle thump, which is how every NES boss room in history got its kick.

THE MUSIC
---------
Retro Bowl's theme is HeatleyBros' "8 Bit Joy" (2017) — bright, major-key,
perky NES.  We are not copying it; we are writing in that idiom and bending it,
which is exactly what Pete asked for.

The bend is MODE.  HeatleyBros is Ionian (plain major).  Medieval music is
modal, and the mode that reads as "medieval" to a modern ear is DORIAN — a minor
scale with a raised sixth, which is why every folk tune about a battle sounds
the way it does.  So the melody is in D Dorian and keeps the perky NES rhythm:
the pulse and the phrasing say arcade, the mode says 1350.

ONE MELODY, FOUR ARRANGEMENTS — Pete's plan, and the whole reason the boss idea
works.  You recognise the tune and the room has changed around it:

    club       112 BPM, Dorian.  Triangle and one soft pulse.  Sparse.
    cup        140 BPM, Dorian.  War drums enter.  Both pulses.
    final      168 BPM, Dorian.  Arpeggiated power chords, double-time war
               drums, 12.5 % duty lead.  8-bit metal.
    champion   150 BPM, and the tune lifts out of Dorian into MAJOR — F natural
               becomes F sharp.  A fanfare that is the same melody you have been
               hearing all game, finally in the bright mode.  That lift is the
               oldest trick in game music and it still works.
"""

import numpy as np
import wave, os, sys

SR = 44100

# --------------------------------------------------------------- the console
# Equal temperament, A4 = 440.  Note names as "D4", "F#3", or None for a rest.
_STEP = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}


def hz(note):
    if note is None:
        return 0.0
    name = note[0].upper()
    i = 1
    semis = _STEP[name]
    while i < len(note) and note[i] in "#b":
        semis += 1 if note[i] == "#" else -1
        i += 1
    octave = int(note[i:])
    return 440.0 * (2.0 ** ((semis + (octave - 4) * 12 - 9) / 12.0))


def pulse(freq, n, duty=0.5, detune=0.0):
    """A square wave with a duty cycle.  12.5 % is thin and buzzy (the classic
    NES lead), 50 % is fat and hollow.  Phase-accumulated rather than computed
    from t, so a frequency that changes mid-note does not click."""
    if freq <= 0:
        return np.zeros(n, dtype=np.float32)
    f = np.full(n, freq * (1.0 + detune), dtype=np.float64)
    phase = np.cumsum(f) / SR
    return np.where((phase % 1.0) < duty, 1.0, -1.0).astype(np.float32)


def triangle(freq, n, steps=16):
    """The NES triangle is STEPPED — 16 levels — which is why it sounds slightly
    gritty rather than pure.  Quantising it is the difference between a bass that
    sounds like a console and one that sounds like a sine."""
    if freq <= 0:
        return np.zeros(n, dtype=np.float32)
    phase = (np.arange(n) * freq / SR) % 1.0
    tri = 2.0 * np.abs(2.0 * (phase - np.floor(phase + 0.5))) - 1.0
    return (np.round(tri * (steps / 2)) / (steps / 2)).astype(np.float32)


def noise(n, period=1, seed=0):
    """A 15-bit LFSR, the same shape the 2A03 uses.  A short period is a hiss
    (hats), a long one is a rumble (war drums).  Generated by holding a random
    value for `period` samples rather than filtering white noise, because the
    holding is what gives it the metallic pitch the console has."""
    rng = np.random.default_rng(seed)
    hold = max(1, int(period))
    raw = rng.integers(0, 2, size=(n // hold) + 1).astype(np.float32) * 2.0 - 1.0
    return np.repeat(raw, hold)[:n]


def env(n, attack=0.002, decay=0.0, sustain=1.0, release=0.05):
    """A NES envelope is a handful of volume steps, so this is deliberately
    blunt.  Release matters most: without it every note ends in a click."""
    e = np.ones(n, dtype=np.float32) * sustain
    a = min(int(attack * SR), n)
    if a > 0:
        e[:a] = np.linspace(0.0, 1.0, a)
    if decay > 0:
        d = min(int(decay * SR), n - a)
        if d > 0:
            e[a:a + d] = np.linspace(1.0, sustain, d)
    r = min(int(release * SR), n)
    if r > 0:
        e[-r:] *= np.linspace(1.0, 0.0, r)
    return e


def vibrato(freq, n, depth=0.0028, rate=5.0, delay=0.22):
    """Pitch wobble that starts LATE and shallow.  A vibrato present from the
    attack sounds like a broken oscillator; one that arrives a fifth of a second
    in sounds like a player.  Depth more than halved after the first pass — at
    0.6 % it was audible as pitch instability rather than as expression."""
    t = np.arange(n) / SR
    on = np.clip((t - delay) * 6.0, 0.0, 1.0)
    return freq * (1.0 + depth * on * np.sin(2 * np.pi * rate * t))


# ------------------------------------------------------------------ the score
class Song:
    """A fixed-length buffer per channel.  Everything is written by absolute
    beat, so an arrangement is a list of what happens rather than a sequence to
    step through — which is what lets four arrangements share one melody."""

    def __init__(self, bpm, bars, beats_per_bar=4, swing=0.0):
        self.bpm = bpm
        self.spb = 60.0 / bpm
        ## SWING BELONGS TO ONE TRACK. `hosted` is the only celebration in the
        ## game and it is the only thing here that swings — every off-eighth is
        ## pushed late by this fraction of a beat, which is the single cheapest
        ## way to make an arrangement unmistakable for its neighbors. Applied
        ## on the clock rather than in the writing, so the drums, the bass and
        ## the tune all lean together instead of one of them sitting square.
        self.swing = swing
        self.beats = bars * beats_per_bar
        self.n = int(self.beats * self.spb * SR) + SR // 2
        self.ch = {k: np.zeros(self.n, dtype=np.float32)
                   for k in ("p1", "p2", "tri", "noi")}

    def at(self, beat):
        if self.swing:
            f = beat % 1.0
            if abs(f - 0.5) < 1e-6:
                beat += self.swing
        return int(beat * self.spb * SR)

    def add(self, chan, beat, buf, gain=1.0):
        i = self.at(beat)
        j = min(self.n, i + len(buf))
        if j > i:
            self.ch[chan][i:j] += buf[:j - i] * gain

    # -- voices -----------------------------------------------------------
    def lead(self, beat, note, beats, duty=0.5, gain=0.22, vib=False, chan="p1"):
        """VIBRATO IS OFF BY DEFAULT, and that is the fix for the warble.

        It used to be on for every lead note in every track. On a sparse
        clubhouse loop that is a nice touch; on the final — where the lead is
        12.5 % duty, doubled an octave down, over arpeggios — five wobbling
        oscillators at slightly different rates is a mess, and Pete called it
        exactly: *"too chaotic, especially with that warble sound in there."*
        Held notes in the champion fanfare were the same thing, exposed.

        Real NES vibrato is applied by hand, to long notes, sparingly. So it is
        opt-in now, shallower, and `long_notes_only` below is what actually uses
        it."""
        if note is None:
            return
        n = max(1, int(beats * self.spb * SR))
        f = hz(note)
        wave_ = self._fm_pulse(f, n, duty) if vib else pulse(f, n, duty)
        self.add(chan, beat, wave_ * env(n, 0.004, 0.05, 0.85, min(0.06, beats * self.spb * 0.4)), gain)

    def _fm_pulse(self, f, n, duty):
        ph = np.cumsum(vibrato(f, n)) / SR
        return np.where((ph % 1.0) < duty, 1.0, -1.0).astype(np.float32)

    def bass(self, beat, note, beats, gain=0.30):
        if note is None:
            return
        n = max(1, int(beats * self.spb * SR))
        self.add("tri", beat, triangle(hz(note), n) * env(n, 0.002, 0.0, 1.0, 0.03), gain)

    def arp(self, beat, notes, beats, rate_hz=60.0, duty=0.25, gain=0.16, chan="p2"):
        """8-BIT METAL, and it is not an effect — it is the technique.  A NES
        cannot hold a chord on one channel, so a power chord is faked by cycling
        root/fifth/octave faster than the ear separates them, and it reads as one
        buzzing, distorted note.  Precisely how Mega Man and Castlevania sound
        like electric guitars.

        THE RATE IS IN HERTZ, NOT BEATS, and that is the second half of the
        warble fix.  A real NES steps the arpeggio once per video frame — 60 Hz,
        about 17 ms — which is comfortably above the rate at which the ear stops
        hearing separate notes.  Specifying it in BEATS meant the rate moved with
        the tempo and drifted into the worst possible band: the champion cue ran
        at 31 Hz and the final at 45 Hz, both too fast to be melody and too slow
        to fuse.  That is not a chord, it is a trill, and it is what Pete heard
        warbling.        THE PHASE MUST BE CONTINUOUS ACROSS THE STEPS, and getting that wrong
        is what made this sound like a weapon.

        The first version built each step by calling `pulse()` afresh, so the
        oscillator SNAPPED BACK TO PHASE ZERO sixty times a second. That edge is
        not part of any of the three notes — it is an impulse train at the step
        rate, and an impulse train has energy at every harmonic of itself all the
        way up through the audible range. Pete, twice: *"that warble sound"*, and
        then *"a gun ray of sound into my ears."* He was describing a 60 Hz buzz
        with a full harmonic stack on it, because that is precisely what it was.

        Measured: 50 ms of arpeggio contained an extra discontinuity every 16.7
        ms that no waveform in it accounted for.

        A real NES has no such artefact, and not because it is careful — the
        channel simply keeps oscillating and only its PERIOD register changes.
        So the frequency is built as an array and integrated ONCE. One phase, one
        cumulative sum, no seams.
        """
        total = max(1, int(beats * self.spb * SR))
        step_n = max(48, int(SR / max(1.0, rate_hz)))
        freqs = np.empty(total, dtype=np.float64)
        pos, k = 0, 0
        while pos < total:
            m = min(step_n, total - pos)
            freqs[pos:pos + m] = hz(notes[k % len(notes)])
            pos += m
            k += 1
        phase = np.cumsum(freqs) / SR
        out = np.where((phase % 1.0) < duty, 1.0, -1.0).astype(np.float32)
        self.add(chan, beat, out * env(total, 0.003, 0.0, 1.0, 0.04), gain)

    def chord(self, beat, notes, beats, duty=0.5, gain=0.10, chan="p2",
              spread=0.0012):
        """A POWER CHORD THAT IS ACTUALLY A CHORD.

        This replaces the arpeggio, and the reason is measured rather than
        aesthetic. Cycling three pitches at 48-60 Hz does not just sound like a
        chord — it FREQUENCY-MODULATES the oscillator at 48-60 Hz, which throws
        sidebands either side of every harmonic. Those sidebands are inharmonic
        by construction:

            a held square          0.4 - 1.0 % inharmonic energy
            the same notes arped   37 - 55 %

        Fifty per cent inharmonic content is a ring modulator. Pete described it
        four separate ways — warble, chaotic, *"a gun ray of sound into my
        ears"*, still there — and every one of them was right. I kept fixing how
        the arpeggio was BUILT (the phase seam was a real bug and worth fixing)
        without questioning whether to use one at all.

        THE TECHNIQUE WAS NEVER THE REQUIREMENT. A NES arpeggiates because it has
        five voices and cannot hold a chord. We are writing 8-bit-STYLED music in
        Python with as many oscillators as we want, so the honest thing is to
        hold the notes — which is also closer to what a real power chord is. Same
        weight, same square-wave character, none of the modulation.

        `spread` detunes each voice a fraction of a percent so the stack thickens
        instead of phasing — the one trick borrowed from analogue rather than
        from the console."""
        n = max(1, int(beats * self.spb * SR))
        e = env(n, 0.006, 0.03, 0.92, min(0.05, beats * self.spb * 0.3))
        for i, note in enumerate(notes):
            f = hz(note) * (1.0 + spread * (i - (len(notes) - 1) / 2.0))
            self.add(chan, beat, pulse(f, n, duty) * e, gain / max(1.0, len(notes) ** 0.7))

    # -- percussion -------------------------------------------------------
    def kick(self, beat, gain=0.55, drop=(150.0, 45.0), dur=0.11):
        """Triangle with the pitch dropping off a cliff — the NES kick.  The
        noise channel alone gives you a click, not a thump."""
        n = int(dur * SR)
        f = np.linspace(drop[0], drop[1], n)
        ph = np.cumsum(f) / SR
        body = (2.0 * np.abs(2.0 * ((ph % 1.0) - 0.5)) - 1.0).astype(np.float32)
        self.add("tri", beat, body * env(n, 0.001, dur * 0.5, 0.25, dur * 0.4), gain)

    def snare(self, beat, gain=0.30, period=3, dur=0.09):
        n = int(dur * SR)
        self.add("noi", beat, noise(n, period, seed=int(beat * 97) & 0xFFFF)
                 * env(n, 0.001, dur * 0.6, 0.15, dur * 0.35), gain)

    def hat(self, beat, gain=0.10, dur=0.028):
        n = int(dur * SR)
        self.add("noi", beat, noise(n, 1, seed=int(beat * 31) & 0xFFFF)
                 * env(n, 0.0005, dur * 0.7, 0.1, dur * 0.25), gain)

    def war(self, beat, gain=0.42, dur=0.20):
        """THE WAR DRUM.  Long-period noise for the skin, a low triangle thump
        underneath for the body.  One without the other is a hiss or a click;
        together they are the thing at the front of a boss room."""
        n = int(dur * SR)
        self.add("noi", beat, noise(n, 9, seed=int(beat * 53) & 0xFFFF)
                 * env(n, 0.002, dur * 0.55, 0.30, dur * 0.4), gain)
        m = int(dur * 0.8 * SR)
        f = np.linspace(96.0, 58.0, m)
        ph = np.cumsum(f) / SR
        body = (2.0 * np.abs(2.0 * ((ph % 1.0) - 0.5)) - 1.0).astype(np.float32)
        self.add("tri", beat, body * env(m, 0.001, 0.05, 0.3, 0.05), gain * 0.8)

    def loop_length(self):
        """Exactly the written bars, with the half-second working pad cut off.

        A LOOP MUST END WHERE IT BEGINS. The pad exists so a note released on the
        last beat has somewhere to ring; shipping it means the file ends in
        silence and the loop dips audibly every time it comes round. Measured at
        8.5 dB on the club track before this existed."""
        return int(self.beats * self.spb * SR)

    def mix(self, levels=None, loop=True):
        lv = {"p1": 0.95, "p2": 0.80, "tri": 1.0, "noi": 0.85}
        if levels:
            lv.update(levels)
        out = sum(self.ch[k] * lv[k] for k in self.ch)
        if loop:
            out = out[:self.loop_length()]
        peak = float(np.max(np.abs(out))) or 1.0
        return (out / peak * 0.89).astype(np.float32)


def ramp(song, chan, until_beat, floor=0.55):
    """ENTRANCES ARE NEVER SUDDEN — the recipe's rule.

    USED ONLY ON THE ONE-SHOT. It is exactly wrong on a loop: a quiet first bar
    is a dip every time the loop comes round, and the entrance is already handled
    where it belongs — `Audio._begin()` starts a track at -80 dB and tweens it
    up, which can also be interrupted. Baking a second one in means fading twice
    on entry and forever afterwards."""
    i = song.at(until_beat)
    if i <= 0:
        return
    song.ch[chan][:i] *= np.linspace(floor, 1.0, i).astype(np.float32)


def write_wav(path, mono):
    st = np.stack([mono, mono], axis=1)
    pcm = np.clip(st * 32767.0, -32768, 32767).astype("<i2")
    with wave.open(path, "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm.tobytes())


# ================================================================ THE MELODY
# D DORIAN: D E F G A B C.  A minor scale with a RAISED SIXTH (B natural against
# an F), and that one note is the whole medieval flavour — it is why a tune in
# this mode sounds like a battle song from 1350 and the same tune in plain minor
# sounds like a lament.  HeatleyBros' idiom is bright Ionian; keeping his rhythm
# and phrasing while changing only the mode is the fusion Pete asked for.
#
# (beat, note, length) at 4 beats to the bar, 16 bars.  Phrase A is the hook,
# phrase B answers it and climbs; A returns; a cadence that lands on the open
# fifth rather than the third, which is the other thing that reads as old.
PHRASE_A = [
    (0.0, "D5", 1.0), (1.0, "A4", 0.5), (1.5, "D5", 0.5),
    (2.0, "F5", 1.0), (3.0, "E5", 1.0),
    (4.0, "D5", 1.5), (5.5, "C5", 0.5), (6.0, "A4", 2.0),
    (8.0, "F4", 1.0), (9.0, "G4", 0.5), (9.5, "A4", 0.5),
    (10.0, "C5", 1.0), (11.0, "A4", 1.0),
    (12.0, "G4", 1.5), (13.5, "F4", 0.5), (14.0, "D4", 2.0),
]
PHRASE_B = [
    (0.0, "A4", 0.5), (0.5, "C5", 0.5), (1.0, "D5", 1.0),
    (2.0, "E5", 1.0), (3.0, "F5", 1.0),
    (4.0, "G5", 1.5), (5.5, "F5", 0.5), (6.0, "E5", 2.0),
    (8.0, "F5", 0.5), (8.5, "E5", 0.5), (9.0, "D5", 1.0),
    (10.0, "B4", 1.0), (11.0, "C5", 1.0),      # B natural — the Dorian sixth
    (12.0, "D5", 2.0), (14.0, "A4", 2.0),
]

# The bass walks the mode rather than pumping a root, which is what keeps a
# 16-bar loop from wearing out.
BASS_A = ["D2", "D2", "F2", "E2", "D2", "D2", "A1", "A1",
          "F2", "F2", "C2", "C2", "G1", "G1", "D2", "D2"]
BASS_B = ["A1", "A1", "D2", "D2", "E2", "E2", "F2", "F2",
          "G2", "G2", "E2", "E2", "D2", "D2", "A1", "A1"]

# Power chords for the metal arrangement: root, fifth, octave.
CHORD = {
    "D": ["D3", "A3", "D4"], "A": ["A2", "E3", "A3"], "F": ["F3", "C4", "F4"],
    "E": ["E3", "B3", "E4"], "C": ["C3", "G3", "C4"], "G": ["G2", "D3", "G3"],
    "B": ["B2", "F#3", "B3"],
    ## Phrygian needs a flat second and a flat seventh, and neither exists in
    ## D Dorian — these belong to the boss theme alone.
    "Eb": ["D#3", "A#3", "D#4"], "Bb": ["A#2", "F3", "A#3"],
}
PROG_A = ["D", "D", "F", "E", "D", "D", "A", "A",
          "F", "F", "C", "C", "G", "G", "D", "D"]
PROG_B = ["A", "A", "D", "D", "E", "E", "F", "F",
          "G", "G", "E", "E", "D", "D", "A", "A"]


# ============================================================== THE BOSS THEME
# A DIFFERENT SONG, and Pete was right to ask for one.
#
# The set's conceit is one melody arranged four ways, and for the clubhouse, cup
# night and the champion cue that is exactly right — it is the club's own theme
# and hearing it change is the point. Applied to the final it produced, in his
# words, *"literally just Cup Knight sped up"*, and that is a fair reading of
# what it was: same phrases, same form, 24 BPM faster.
#
# **A boss should not sound like your own theme.** It is the thing in front of
# you, not you. So the final gets its own music, and the contrast is written into
# the material rather than into the tempo:
#
#   MODE      the set is D DORIAN, which is a minor scale with a bright raised
#             sixth. The boss is D PHRYGIAN — the same root, but with a FLAT
#             SECOND. That one semitone leaning onto the tonic is the most
#             menacing interval in common use and the reason half of metal is
#             written in this mode. Same key center, opposite character.
#   SHAPE     the club theme is a MELODY: it breathes, it phrases, it cadences.
#             The boss is a RIFF — an eight-beat ostinato that hammers and does
#             not resolve. A tune you could hum against a figure you cannot get
#             away from.
#   HARMONY   i - bII - bVII - i. The flat-two chord is the Phrygian sound and
#             it does not exist anywhere else in this set.

## The ostinato. Eight beats, driven in eighths, always present — this is the
## thing the player will remember, and it never lets go.
RIFF = [
    (0.0, "D3", 0.5), (0.5, "D3", 0.5), (1.0, "D#3", 0.5), (1.5, "D3", 0.5),
    (2.0, "F3", 0.5), (2.5, "D3", 0.5), (3.0, "C3", 0.5), (3.5, "D3", 0.5),
    (4.0, "D3", 0.5), (4.5, "D3", 0.5), (5.0, "D#3", 0.5), (5.5, "F3", 0.5),
    (6.0, "D#3", 1.0), (7.0, "D3", 1.0),
]

## The lead over it: angular, and it leans on the flat second every time.
BOSS_A = [
    (0.0, "A4", 1.0), (1.0, "A#4", 0.5), (1.5, "A4", 0.5),
    (2.0, "F4", 1.0), (3.0, "D#4", 1.0),
    (4.0, "D4", 1.5), (5.5, "D#4", 0.5), (6.0, "F4", 2.0),
]
## And the climb — the half of the theme that goes somewhere, so eight bars of
## riff does not become wallpaper.
BOSS_B = [
    (0.0, "D5", 0.5), (0.5, "D#5", 0.5), (1.0, "F5", 1.0),
    (2.0, "D#5", 0.5), (2.5, "D5", 0.5), (3.0, "C5", 1.0),
    (4.0, "A#4", 1.0), (5.0, "A4", 1.0), (6.0, "D5", 2.0),
]
## i - bII - bVII - i, twice. The flat two is the whole flavour.
BOSS_PROG = ["D", "D", "Eb", "Eb", "Bb", "Bb", "D", "D"]


def ficta(phrase):
    """MUSICA FICTA — raise F to F# when the line steps up into G.

    Not an effect and not borrowed from anywhere: this is what singers actually
    did in the fourteenth century, and the reason it is written out here rather
    than into the mode is that it is a RULE ABOUT MOTION, not a scale degree.
    D Dorian has an F natural; a line ascending F->G sharpens it, because the
    half step pulls into the note it is heading for. Descending, it stays flat.

    Two consequences, both wanted. It is period-correct — the set's whole claim
    is a folk mode with a raised sixth, and ficta is the other half of that
    practice. And it puts a little major color in a minor set, at cadence
    points, which is what stops the front door and the clubhouse sounding like
    two different games.

    Only F->G, only ascending, only when the two are adjacent in time."""
    out = []
    for i, (b, note, ln) in enumerate(phrase):
        nxt = phrase[i + 1] if i + 1 < len(phrase) else None
        if (note is not None and nxt is not None and nxt[1] is not None
                and note[:-1] == "F" and nxt[1][:-1] == "G"
                and abs((b + ln) - nxt[0]) < 1e-6
                and hz(nxt[1]) > hz(note)):
            note = transpose(note, 1)
        out.append((b, note, ln))
    return out


def walk(line):
    """ROOT, FIFTH, OCTAVE, FIFTH — where `bounce()` gives root-octave-root.

    The difference matters more than it looks: a bounce is a pulse and a walk is
    a LINE, so the two read as different instruments playing different parts
    even under the same tune. `menu` walks and `club` bounces, and that is one
    of the three things now keeping them apart."""
    out = []
    for note in line:
        out += [note, transpose(note, 7), transpose(note, 12), transpose(note, 7)]
    return out


def major_lift(note):
    """DORIAN -> IONIAN.  F becomes F#, C becomes C#, and the tune you have been
    hearing all game arrives in the bright mode.  This is the oldest device in
    game music — the victory version of the theme — and it still works because
    the listener has earned the resolution over several hours."""
    if note is None:
        return None
    if note[0].upper() == "F" and "#" not in note:
        return "F#" + note[1:]
    if note[0].upper() == "C" and "#" not in note:
        return "C#" + note[1:]
    return note


def lay_melody(song, at, phrase, duty=0.5, gain=0.22, lift=False, chan="p1", vib=False):
    for (b, note, ln) in phrase:
        song.lead(at + b, major_lift(note) if lift else note, ln,
                  duty=duty, gain=gain, vib=vib, chan=chan)


def lay_bass(song, at, line, per=1.0, gain=0.30, lift=False):
    for i, note in enumerate(line):
        song.bass(at + i * per, major_lift(note) if lift else note, per, gain)




# ================================================================== THE FORM
# THE BUG THIS EXISTS TO STOP.
#
# A phrase is 16 beats — four bars. The first version of these arrangements laid
# PHRASE_A and PHRASE_B once each, eight bars in total, into a song declared as
# THIRTY-TWO bars. The remaining twenty-four bars had a full drum kit and no
# music whatsoever, on every track in the set.
#
# Pete heard it immediately: *"They all started off good, but tailed off hard
# with just the drums in the middle."* Measured afterwards at **75% of every
# loop**. Nothing caught it because nothing was looking — the renderer is happy
# to write silence and the mastering chain is happy to normalise it.
#
# So an arrangement is now a FORM: an explicit list of which phrase plays in
# each four-bar slot and how it is voiced. A song's length is derived from the
# form rather than declared next to it, which makes the two impossible to
# disagree, and `check_holes()` fails the build if any slot comes out empty.

## WHY 112 FELT SLOW WHEN IT WAS NOT.
##
## Pete: *"What BPM is Retro Bowl? it seems much faster than 112."* Measured:
## HeatleyBros' "8 Bit Joy" is **115 BPM in G major** — so the tempo was already
## within three beats of the reference and was never the problem.
##
## What makes that track feel fast is NOTE DENSITY. Its lead is in constant
## eighth-note motion and its bass bounces root-octave underneath; ours held
## notes for two whole beats and put a root on every bar. Same tempo, half the
## events, and the ear reads events rather than metronome marks. (The tempo
## services even list it as playable "double-time at 230" — which is the same
## observation from the other side: the sixteenth pulse is what you feel.)
##
## So the fix is writing, not tempo. `busy()` subdivides a held note into
## movement using the mode's own neighbors, which keeps the melody recognizable
## — it is still the same tune, it just never stops moving.
NEIGHBOR = ["D", "E", "F", "G", "A", "B", "C"]


def step_in_mode(note, steps):
    """Move up or down the D Dorian scale by degree, not by semitone — which is
    what keeps a passing note inside the mode and stops the medieval flavour
    leaking out through an accidental."""
    if note is None or steps == 0:
        return note
    name = note[0].upper()
    acc = "#" if "#" in note else ""
    octave = int(note[-1])
    ## THE OCTAVE BOUNDARY IS AT C, AND THE LIST STARTS AT D.
    ##
    ## Scientific pitch notation rolls the octave number over at C, not at the
    ## root of whatever mode you are in — so in a D-rooted list, C is the one
    ## degree that belongs to the octave ABOVE the D it sits with. Ignoring that
    ## put a passing note a full octave below where it belonged: D5 stepped down
    ## by one came out as C4 instead of C5, which is not a neighbor tone, it is
    ## a leap out of the phrase.
    i = NEIGHBOR.index(name) if name in NEIGHBOR else 0
    j = i + steps
    out = NEIGHBOR[j % len(NEIGHBOR)]
    octave += j // len(NEIGHBOR)
    if out == "C":
        octave += 1
    return out + acc + str(octave)


def busy(phrase, min_len=1.0, shape=(0, 1)):
    """Subdivide anything held for `min_len` or longer into eighths that walk
    the mode. `shape` is the degree offsets to cycle through: (0, 1) is a
    neighbor-tone bounce, (0, 2) an arpeggio lift, (0, -1) a lean downward."""
    out = []
    for (b, note, ln) in phrase:
        if note is None or ln < min_len:
            out.append((b, note, ln))
            continue
        steps = int(round(ln / 0.5))
        for k in range(steps):
            out.append((b + k * 0.5,
                        step_in_mode(note, shape[k % len(shape)]), 0.5))
    return out


def bounce(line):
    """A NES bassline does not sit on a root — it bounces root/octave, which is
    most of why the console's low end sounds like it is running rather than
    standing. Returns twice as many notes at half the length."""
    out = []
    for note in line:
        up = note[0] + (note[1] if note[1] in "#b" else "") + str(int(note[-1]) + 1)
        out.extend([note, up])
    return out


def transpose(note, semis):
    if note is None or semis == 0:
        return note
    f = hz(note) * (2.0 ** (semis / 12.0))
    # Back to the nearest named note, sharps only.
    n = int(round(12 * np.log2(f / 440.0))) + 9 + 48
    names = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
    return names[n % 12] + str(n // 12)


## One four-bar slot. `phrase` is "A" or "B"; everything else is voicing.
## THE MENU'S ANSWERING FIGURE — three notes that reply to the tune in its own
## sustains. It is the one piece of melodic material in the whole set that
## belongs to a single track, and it is what stops the title screen from being
## the clubhouse at a slightly different tempo.
ANSWER_A = [(6.5, "D5", 0.5), (7.0, "E5", 0.5), (7.5, "F5", 0.5),
            (14.5, "A4", 0.5), (15.0, "C5", 0.5), (15.5, "D5", 0.5)]
ANSWER_B = [(6.5, "C5", 0.5), (7.0, "D5", 0.5), (7.5, "E5", 0.5),
            (14.5, "F4", 0.5), (15.0, "G4", 0.5), (15.5, "A4", 0.5)]


def Slot(phrase, duty=0.5, gain=0.20, oct_=0, counter=None, arp=False,
         bass_sub=1.0, lift=False, bass_gain=0.28, busy_shape=None,
         bass_bounce=False, bass_walk=False, double=None, stac=None,
         answer=None, ficta_=False):
    """`bass_walk`, `double`, `stac` and `answer` all exist for one reason:
    three tracks had come out as the same arrangement at three tempos.

    `busy_shape` + `bass_bounce` + a 50 % duty + a full kit was the ONLY way to
    write a bright track here, so every bright track was written that way and
    they measured 0.90+ against each other. These are the other ways."""
    return dict(phrase=phrase, duty=duty, gain=gain, oct=oct_, counter=counter,
                arp=arp, bass_sub=bass_sub, lift=lift, bass_gain=bass_gain,
                busy_shape=busy_shape, bass_bounce=bass_bounce,
                bass_walk=bass_walk, double=double, stac=stac, answer=answer,
                ficta=ficta_)


## THE HIGHEST NOTE ANY ARRANGEMENT MAY WRITE.
##
## Pete: *"Theres some high pitched parts in the menu song that cringe my ear."*
## Counted off the score rather than guessed at from a spectrum, the menu wrote
## **34 of its 291 notes above A5 — 12 %, the highest proportion in the set** —
## and reached A6 repeatedly. Not because anybody chose A6, but because an
## octave shift, a busy pass and a counter-line each moved a note up a little and
## nothing was watching the total.
##
## So there is a ceiling, and anything over it drops an octave rather than being
## refused: a melody that wants to rise should still rise, it just does it in a
## register a person can sit with for ten minutes. C6 is the top of a comfortable
## soprano and about where a 50 % square stops being bright and starts being
## piercing.
NOTE_PC = {n: i for i, n in enumerate(
    ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"])}

CEILING = "C6"


def capped(note):
    if note is None:
        return None
    top = hz(CEILING)
    while note is not None and hz(note) > top:
        note = transpose(note, -12)
    return note


def lay_form(song, form, start=0.0, arp_gain=0.15, arp_rate=60.0, arp_duty=0.25):
    """Write a whole arrangement. Returns the beat it ends on, which is what the
    caller uses to size the song — so the form and the length cannot drift."""
    at = start
    for slot in form:
        base_phrase = PHRASE_A if slot["phrase"] == "A" else PHRASE_B
        ## Ficta first, so the counter-line inherits it. The counter reads
        ## `base_phrase`, and a harmony that kept the F natural against a
        ## sharpened melody is a semitone clash, not a harmony.
        if slot["ficta"]:
            base_phrase = ficta(base_phrase)
        phrase = base_phrase
        if slot["busy_shape"] is not None:
            phrase = busy(phrase, shape=slot["busy_shape"])
        bassline = BASS_A if slot["phrase"] == "A" else BASS_B
        if slot["bass_bounce"]:
            bassline = bounce(bassline)
        elif slot["bass_walk"]:
            bassline = walk(bassline)
        prog = PROG_A if slot["phrase"] == "A" else PROG_B
        lift = slot["lift"]

        stac = slot["stac"]
        for (b, note, ln) in phrase:
            if note is None:
                continue
            n2 = capped(transpose(major_lift(note) if lift else note, slot["oct"] * 12))
            ln2 = ln * stac if stac else ln
            song.lead(at + b, n2, ln2, duty=slot["duty"], gain=slot["gain"])
            ## An octave double is weight without brightness — the same note
            ## underneath, never above, so it cannot push anything toward the
            ## ceiling. It is what lets the menu state the tune plainly and
            ## still sound like the biggest thing in the set.
            if slot["double"] is not None:
                song.lead(at + b, capped(transpose(n2, int(slot["double"]))), ln2,
                          duty=slot["duty"], gain=slot["gain"] * 0.45, chan="p2")

        ## CALL AND RESPONSE. The answer lands in the tune's own sustains
        ## instead of underneath it, which is a different thing from a counter
        ## line and belongs to exactly one track.
        for (b, note, ln) in (slot["answer"] or []):
            song.lead(at + b, capped(note), ln, duty=0.5, gain=0.135, chan="p2")

        ## The counter-line is what keeps a repeated phrase from being a repeat.
        ## THE COUNTER IS TAKEN FROM THE ORIGINAL PHRASE, NOT THE BUSIED ONE.
        ##
        ## It used to read whatever `phrase` had become, so on a slot with both
        ## `busy_shape=(0, 2)` and a counter a fifth above, the two lifts
        ## COMPOUNDED: a G5 in the melody became B5 through the busy pass and
        ## then F#6 in the harmony. Nobody wrote "put a note at F#6" — it fell
        ## out of two reasonable decisions multiplying.
        c = slot["counter"]
        if c is not None:
            for (b, note, ln) in base_phrase:
                if note is None:
                    continue
                n2 = capped(transpose(major_lift(note) if lift else note, int(c["semis"])))
                song.lead(at + b, n2, ln, duty=c.get("duty", 0.125),
                          gain=c.get("gain", 0.07), chan="p2",
                          vib=c.get("vib", False))

        sub = slot["bass_sub"]
        steps = int(round(1.0 / sub))
        per = 16.0 / len(bassline)          ## a bounced line is twice as long
        for i, note in enumerate(bassline):
            n2 = transpose(major_lift(note) if lift else note, 0)
            for k in range(steps):
                song.bass(at + i * per + k * sub * per, n2, sub * per,
                          gain=slot["bass_gain"] * (1.0 if k == 0 else 0.62))

        if slot["arp"]:
            for i, ch in enumerate(prog):
                notes = CHORD[ch]
                if lift and ch in ("D", "F"):
                    notes = CHORD["D"]
                ## Root and fifth only. The octave on top was the third voice in
                ## a stack of squares and it is the one that turns weight into
                ## clutter — a guitar power chord is two notes for the same
                ## reason.
                song.chord(at + i, notes[:2], 1.0, duty=arp_duty, gain=arp_gain)
        at += 16.0
    return at


def sized(bpm, form, tail_beats=0.0, swing=0.0):
    """A song exactly as long as its form. The length is DERIVED, which is the
    whole fix: there is no second number to get wrong."""
    beats = len(form) * 16.0 + tail_beats
    return Song(bpm, int(round(beats / 4.0)), swing=swing)


# =========================================================== ARRANGEMENT 1/4
def club(bpm=118):
    """THE CLUBHOUSE, and the only track in the set whose job is to be IGNORED —
    it plays for minutes on end while somebody reads a team sheet.

    118 BPM, three above HeatleyBros' measured 115; the tempo was never the
    problem. What makes "8 Bit Joy" feel fast is that its lead never stops
    moving and its bass bounces root-octave underneath, so every slot here is
    written `busy` over a bouncing bass and the tune just runs.

    **What changed is the weight.** Menu and hosted were both written the same
    way — busy, bouncing, 50 % duty, full kit — and the three of them measured
    0.90+ against each other. Club is the one that should give ground, because
    constant motion and constant PROMINENCE are different things and only the
    first is in its job description. So: **25 % duty throughout**, where menu is
    50 %, and the sparsest kit in the set — kick, a snare on four, hats on the
    quarters, no fills at all. Thin and moving, which is what furniture music
    is. The dynamics still do not move; the volume does."""
    form = [
        Slot("A", duty=0.25, gain=0.175, busy_shape=(0, 1), bass_bounce=True, ficta_=True),
        Slot("A", duty=0.25, gain=0.175, busy_shape=(0, 1), bass_bounce=True,
             counter={"semis": -5, "gain": 0.05, "duty": 0.25}),
        Slot("B", duty=0.25, gain=0.175, busy_shape=(0, 2), bass_bounce=True),
        Slot("B", duty=0.25, gain=0.165, busy_shape=(0, 1), bass_bounce=True,
             counter={"semis": -12, "gain": 0.055}),
        Slot("A", duty=0.25, gain=0.175, oct_=-1, busy_shape=(0, -1), bass_bounce=True,
             counter={"semis": 12, "gain": 0.045}),
        Slot("B", duty=0.25, gain=0.175, busy_shape=(0, 1), bass_bounce=True,
             counter={"semis": -5, "gain": 0.06, "duty": 0.25}),
        Slot("A", duty=0.25, gain=0.185, busy_shape=(0, 2), bass_bounce=True,
             counter={"semis": 7, "gain": 0.05}),
        Slot("A", duty=0.25, gain=0.175, busy_shape=(0, 1), bass_bounce=True,
             bass_gain=0.24, ficta_=True),
    ]
    s = sized(bpm, form)
    lay_form(s, form)
    ## The sparsest kit in the set, on purpose. No snare on two, no fills, hats
    ## on the quarters. A kit that announces itself is a kit you notice, and
    ## this is the one track nobody should notice.
    for bar in range(int(s.beats // 4)):
        base = bar * 4
        s.kick(base, 0.30)
        s.kick(base + 2, 0.24)
        s.snare(base + 3, 0.15, period=2)
        for e in (0, 1, 2, 3):
            s.hat(base + e, 0.035)
    return s


# =========================================================== ARRANGEMENT 2/4
def cup(bpm=146):
    """CUP NIGHT. **Pete likes this one**, so it is changed as little as
    possible: the vibrato is gone (it was on every lead note in every track), the
    arpeggios now fuse properly at 60 Hz, and the tempo moves 140 -> 146 to stay
    a clear step above the clubhouse now that the clubhouse runs at 118. The
    slots, the voicings and the drum pattern are untouched.

    Same eight slots, and the WAR DRUMS arrive.
    The tune thins to 25% duty and picks up a harmony a fourth above; the bass
    runs eighths throughout. Two slots go full — arpeggios under the melody — so
    the loop has a peak in it rather than a plateau."""
    form = [
        Slot("A", duty=0.25, gain=0.21, bass_sub=0.5, ficta_=True),
        Slot("A", duty=0.25, gain=0.21, bass_sub=0.5,
             counter={"semis": 5, "gain": 0.075, "duty": 0.125}),
        Slot("B", duty=0.25, gain=0.21, bass_sub=0.5),
        Slot("B", duty=0.25, gain=0.21, bass_sub=0.5, arp=True,
             counter={"semis": 5, "gain": 0.075, "duty": 0.125}),
        ## CAUGHT BY check_no_harsh_section ON ITS FIRST RUN, which is the whole
        ## reason it exists: a 12.5 % duty lead an OCTAVE UP is the brightest
        ## combination available on this console, and it measured 6.0 % against
        ## this track's 3.3 % median. It would have shipped. Same cure as the
        ## final and the champion — the lift moves to a harmony a fifth above and
        ## the lead stays in its own register.
        Slot("A", duty=0.25, gain=0.21, bass_sub=0.5,
             counter={"semis": 7, "gain": 0.08, "duty": 0.5}),
        Slot("B", duty=0.25, gain=0.21, bass_sub=0.5, arp=True),
        Slot("A", duty=0.25, gain=0.22, bass_sub=0.5, arp=True,
             counter={"semis": 5, "gain": 0.08, "duty": 0.125}),
        Slot("A", duty=0.5, gain=0.20, bass_sub=0.5),        # cadence
    ]
    s = sized(bpm, form)
    lay_form(s, form, arp_gain=0.075, arp_rate=48.0, arp_duty=0.5)
    for bar in range(int(s.beats // 4)):
        base = bar * 4
        s.war(base, 0.30)
        s.war(base + 1.5, 0.20)
        s.war(base + 2, 0.26)
        s.snare(base + 3, 0.22)
        for e in (0.5, 1.0, 2.5, 3.5):
            s.hat(base + e, 0.055)
        if bar % 8 == 7:
            for k in range(4):
                s.snare(base + 3.0 + k * 0.25, 0.10 + k * 0.045, period=2)
    return s


# =========================================================== ARRANGEMENT 3/4
def final(bpm=172):
    """THE FINAL — its own song. See THE BOSS THEME above for why.

    Written as a riff piece rather than through the form system, because the
    form system exists to arrange a MELODY across slots and this is not that: it
    is one ostinato that never stops, with things happening over it. Forcing it
    through `lay_form` would have produced a third arrangement of the club theme
    wearing a different hat, which is precisely what Pete rejected.

    Structure, and it is a shape rather than a repeat:

        bars  1-4    the riff alone, with the drums. Nothing else.
        bars  5-12   the lead arrives over it
        bars 13-20   the climb — the half that goes somewhere
        bars 21-24   riff and power chords, no lead. The breakdown.
        bars 25-32   everything

    The riff is on the triangle AND doubled by a low pulse, which is how a NES
    gets a bass part to sound like a rhythm guitar."""
    BARS = 32
    s = Song(bpm, BARS)

    def riff_at(bar, lead_gain=0.0, duty=0.25):
        base = bar * 4.0
        for (b, note, ln) in RIFF:
            s.bass(base + b, note, ln, gain=0.30)
            if lead_gain > 0.0:
                s.lead(base + b, note, ln, duty=duty, gain=lead_gain)

    def line_at(bar, phrase, gain=0.21, duty=0.25, oct_=0):
        base = bar * 4.0
        for (b, note, ln) in phrase:
            s.lead(base + b, transpose(note, oct_ * 12), ln,
                   duty=duty, gain=gain, chan="p1")

    def chords_at(bar, gain=0.105):
        base = bar * 4.0
        for i, ch in enumerate(BOSS_PROG):
            s.chord(base + i, CHORD[ch][:2], 1.0, duty=0.34, gain=gain)

    ## Every two bars is one turn of the riff, all thirty-two bars of it.
    for bar in range(0, BARS, 2):
        ## Bars 1-4 carry the riff on the pulse as well, so the opening has
        ## weight before the lead exists to give it any.
        riff_at(bar, lead_gain=0.13 if bar < 4 else 0.075)

    for bar in range(4, 12, 2):
        line_at(bar, BOSS_A)
        if bar >= 8:
            chords_at(bar)
    for bar in range(12, 20, 2):
        line_at(bar, BOSS_B, gain=0.22)
        chords_at(bar)
    for bar in range(20, 24, 2):
        ## THE BREAKDOWN. No lead at all — riff, chords and drums. The check that
        ## refuses a track with a hole in it passes because the riff is a tune,
        ## which is the difference between a breakdown and the bug in pass one.
        chords_at(bar, gain=0.14)
    for bar in range(24, 32, 2):
        line_at(bar, BOSS_A if bar < 28 else BOSS_B, gain=0.23)
        chords_at(bar, gain=0.115)

    for bar in range(BARS):
        base = bar * 4
        s.kick(base, 0.34)
        s.kick(base + 2, 0.30)
        for beat in range(4):
            s.war(base + beat, 0.30 if beat % 2 == 0 else 0.20)
            s.hat(base + beat + 0.5, 0.045)
        s.snare(base + 1, 0.24)
        s.snare(base + 3, 0.24)
        ## A roll into each eight-bar section, and a longer one into the last.
        if bar % 8 == 7:
            n = 12 if bar == 23 else 8
            for k in range(n):
                s.snare(base + 4.0 - n * 0.25 + k * 0.25, 0.10 + k * 0.028, period=2)
    return s


# =========================================================== ARRANGEMENT 4/5
def worlds(bpm=138):
    """WORLDS — grand rather than fast, and that distinction is the point.

    The boss got its own song because a boss is the thing in front of you. Worlds
    is not: it is still YOUR club, at the biggest thing there is. So it keeps the
    club's melody — and separates itself on a different axis from the final.

        cup     146 BPM   driving
        WORLDS  138 BPM   slower, wider, ceremonial
        final   172 BPM   fast and vicious

    Escalating by tempo alone would have made Worlds a halfway house between
    those two. Making it the SLOWEST of the three big tracks and the widest is
    what lets it feel enormous without competing with the boss.

    THE DRONE IS WHAT MAKES IT SOUND FAR FROM HOME. A sustained open fifth
    running under the whole piece — D and A, never moving — is the oldest device
    in European folk music and the sound of every bagpipe, hurdy-gurdy and
    organum that predates functional harmony by six hundred years. Nothing else
    in this set has one, and it does more for "somewhere else, and old" than any
    amount of orchestration would.

    Under the drone the harmony still moves, which is the tension the whole thing
    runs on: a chord that changes over a bass that will not."""
    form = [
        Slot("A", duty=0.5, gain=0.20, bass_sub=1.0, ficta_=True),
        Slot("A", duty=0.5, gain=0.20, arp=True,
             counter={"semis": 7, "gain": 0.07, "duty": 0.5}),
        Slot("B", duty=0.5, gain=0.21, arp=True),
        Slot("B", duty=0.25, gain=0.21, arp=True,
             counter={"semis": -5, "gain": 0.08, "duty": 0.5}),
        Slot("A", duty=0.5, gain=0.21, arp=True, busy_shape=(0, 2),
             counter={"semis": 7, "gain": 0.075, "duty": 0.5}),
        Slot("B", duty=0.5, gain=0.22, arp=True,
             counter={"semis": 7, "gain": 0.08, "duty": 0.5}),
        Slot("A", duty=0.5, gain=0.22, arp=True,
             counter={"semis": -5, "gain": 0.08, "duty": 0.5}),
        Slot("A", duty=0.5, gain=0.20, bass_sub=1.0, ficta_=True),
    ]
    s = sized(bpm, form)
    lay_form(s, form, arp_gain=0.085, arp_duty=0.5)

    ## THE DRONE, laid in four-bar lengths rather than one long note so the
    ## envelope re-articulates and it breathes like an instrument being played
    ## rather than a tone being held. Low gain: it is the floor, not a part.
    for bar in range(0, int(s.beats // 4), 4):
        ## Louder now that it is Worlds' alone. It was sharing the one
        ## distinctive texture in the set with the title screen, which made both
        ## weaker — so it is turned up and the menu's is gone entirely.
        s.chord(bar * 4.0, ["D2", "A2"], 16.0, duty=0.5, gain=0.115, spread=0.0016)
        s.chord(bar * 4.0, ["D3", "A3"], 16.0, duty=0.5, gain=0.055, spread=0.0020)

    for bar in range(int(s.beats // 4)):
        base = bar * 4
        ## A PROCESSIONAL, not a rock beat. The war drum lands on 1 and 3 with a
        ## pickup into the bar, which is how a march moves — the final's
        ## every-beat pattern would make this frantic, and frantic is what it is
        ## deliberately not.
        s.war(base, 0.34)
        s.war(base + 2, 0.26)
        s.war(base + 3.5, 0.18)
        s.kick(base, 0.30)
        s.snare(base + 2, 0.20)
        for e in (1.0, 3.0):
            s.hat(base + e, 0.05)
        if bar % 8 == 7:
            for k in range(6):
                s.snare(base + 2.5 + k * 0.25, 0.10 + k * 0.035, period=2)
    return s


# =========================================================== ARRANGEMENT 5/5
def champion(bpm=152):
    """THE CHAMPION FANFARE.

    CLEANED UP, same complaint as the final. The held notes were the most
    exposed place in the set for the vibrato — a single sustained pulse wobbling
    against a fanfare is the one thing that cannot hide — and its arpeggios were
    running at 31 Hz, which is a trill, not a chord. Both fixed at source.

    What is left is deliberately simple: rising fifths, the melody LIFTED OUT OF
    DORIAN INTO MAJOR (every F becomes F#, every C becomes C#), and a held major
    chord at the end. A victory cue should be clear, short, and over.

    The counter-lines went with the warble. At this register they were adding
    thickness where the tune wanted air."""
    form = [
        Slot("A", duty=0.5, gain=0.24, lift=True, arp=True, bass_bounce=True),
        Slot("B", duty=0.5, gain=0.24, lift=True, arp=True, bass_bounce=True),
        ## Also had the lead an octave up, and at 6.2% high-frequency share
        ## against the fanfare's 2.0% it was the single harshest moment in the
        ## set. The movement stays; the register comes back down.
        Slot("A", duty=0.5, gain=0.25, lift=True, arp=True,
             busy_shape=(0, 2), bass_bounce=True,
             counter={"semis": 7, "gain": 0.07, "duty": 0.5}),
        Slot("B", duty=0.5, gain=0.25, lift=True, arp=True, bass_bounce=True),
    ]
    s = sized(bpm, form, tail_beats=8.0)
    for i, note in enumerate(["D4", "A4", "D5", "F#5"]):
        s.lead(i * 0.5, note, 0.5, duty=0.5, gain=0.26)
        s.bass(i * 0.5, "D2", 0.5, gain=0.30)
    s.lead(2.0, "A5", 2.0, duty=0.5, gain=0.28)
    s.chord(2.0, CHORD["D"][:2], 2.0, duty=0.5, gain=0.13)
    s.bass(2.0, "D2", 2.0, gain=0.30)

    end = lay_form(s, form, start=4.0, arp_gain=0.08, arp_rate=48.0, arp_duty=0.5)
    ## The last chord is an ARPEGGIO, not three sustained pulses stacked on two
    ## channels. Three held squares beat against each other; one arpeggio is a
    ## chord, and it is how the console would have done it anyway.
    s.lead(end, "D5", 4.0, duty=0.5, gain=0.20)
    ## The last chord is held, not cycled. A fanfare's final chord is the
    ## most exposed sound in the whole set — it is alone, it is long, and it is
    ## what the player remembers. Arpeggiating it put fifty per cent inharmonic
    ## energy on the one note that had nowhere to hide.
    s.chord(end, ["D4", "F#4", "A4"], 4.0, duty=0.5, gain=0.15)
    s.bass(end, "D2", 4.0, gain=0.30)

    for bar in range(int(s.beats // 4)):
        base = bar * 4
        if bar < 1:
            continue
        s.kick(base, 0.34)
        s.kick(base + 2, 0.30)
        s.snare(base + 1, 0.22)
        s.snare(base + 3, 0.22)
        for e in (0.5, 1.5, 2.5, 3.5):
            s.hat(base + e, 0.06)
    ramp(s, "noi", 4.0, 0.0)
    return s


# ======================================================== THE REMAINING THREE
def menu(bpm=129.2):
    """THE TITLE SCREEN — third version, and the second one Pete caught.

    Version one was 100 BPM and sparse, which was a regression on a correction
    he had already given me. Version two fixed the tempo and the density and in
    doing so made it **the clubhouse at 124 BPM**: same busied phrase, same
    bouncing bass, same kit, same 50 % duty. Measured against club it came out
    at 0.92, and against hosted at 0.97. He heard it before I measured it, for
    the third time in this set.

    So the menu is no longer a brighter arrangement of the clubhouse — it is a
    DIFFERENT READING of the same tune, and every lever is set the other way:

    * **The tune is played plainly, not busied.** Club's whole idea is a lead
      that never stops moving; the menu states the melody in long staccato
      notes, about a third the note rate. A title theme is the one that has to
      be singable after ten seconds.
    * **It is octave-doubled** rather than harmonised, so it is heavy without
      being bright, and nothing moves toward the ceiling.
    * **The bass walks** root-fifth-octave-fifth where club bounces.
    * **Call and response** — `ANSWER_A`/`ANSWER_B` reply in the melody's own
      sustains. Nothing else in the set does this.
    * **A march kit**: backbeat snare, kick on the one and the and-of-three, hats
      on quarters. Club's kit is eighths; hosted's swings.

    The two-beat pickup stays. It is the game announcing itself."""
    form = [
        Slot("A", duty=0.5, gain=0.21, stac=0.62, double=-12, bass_walk=True, ficta_=True),
        Slot("A", duty=0.5, gain=0.21, stac=0.62, double=-12, bass_walk=True,
             answer=ANSWER_A, ficta_=True),
        Slot("B", duty=0.5, gain=0.22, stac=0.62, double=-12, bass_walk=True,
             answer=ANSWER_B, ficta_=True),
        Slot("B", duty=0.5, gain=0.22, stac=0.55, double=-12, bass_walk=True,
             counter={"semis": 7, "gain": 0.06, "duty": 0.5}, ficta_=True),
        Slot("A", duty=0.5, gain=0.22, stac=0.62, double=-12, bass_walk=True,
             answer=ANSWER_A, ficta_=True),
        Slot("A", duty=0.5, gain=0.21, stac=0.70, double=-12, bass_walk=True,
             answer=ANSWER_B, ficta_=True),
    ]
    s = sized(bpm, form, tail_beats=2.0)
    for k, note in enumerate(["A4", "C5", "D5"]):
        s.lead(k * 0.5, note, 0.5, duty=0.5, gain=0.22)
    lay_form(s, form, start=2.0)
    ## A MARCH, not a groove. Kick on the one and the and-of-three, snare hard
    ## on two and four, hats on the quarters. The point is that you could walk
    ## to it — the clubhouse you could only fidget to.
    for bar in range(int(s.beats // 4)):
        base = bar * 4
        s.kick(base, 0.36)
        s.kick(base + 2.5, 0.26)
        s.snare(base + 1, 0.21, period=2)
        s.snare(base + 3, 0.21, period=2)
        for e in (0, 1, 2, 3):
            s.hat(base + e, 0.045)
        if bar % 8 == 7:
            for k in range(3):
                s.snare(base + 3.0 + k * 0.3333, 0.11 + k * 0.035, period=2)
    return s


def hosted(bpm=132, swing=0.085):
    """YOUR OWN TOURNAMENT — the one occasion in the game that is a celebration
    rather than a test. You paid for it, it is your hall, and the people in it
    came to see your club.

    **AND IT SWINGS. Nothing else here does.** That is the whole fix: it used to
    measure 0.97 against the menu — identical kit, identical duty, identical
    bouncing bass, six BPM apart — which is to say it was the same arrangement
    with a different tempo marking. Swing changes where every off-eighth lands,
    so the tune, the bass and the kit all lean together and the thing stops
    being comparable to a square track at all. It is also simply what a party
    sounds like.

    The rest of its identity stays: 50 % duty throughout (fat and open, where
    cup night thins to 25 %) and a harmony a THIRD above rather than a fifth —
    the sweeter interval, and the only place in the set it is used. Plus a
    HANDCLAP backbeat, two snares a sixteenth apart, which no other kit has.
    Warm rather than heavy. No war drums anywhere near it."""
    form = [
        Slot("A", duty=0.5, gain=0.20, bass_bounce=True, busy_shape=(0, 1), ficta_=True),
        Slot("A", duty=0.5, gain=0.20, bass_bounce=True, busy_shape=(0, 1), arp=True,
             counter={"semis": 4, "gain": 0.075, "duty": 0.5}),
        Slot("B", duty=0.5, gain=0.21, bass_bounce=True, arp=True),
        Slot("B", duty=0.5, gain=0.21, bass_bounce=True, busy_shape=(0, 2), arp=True,
             counter={"semis": 4, "gain": 0.08, "duty": 0.5}),
        Slot("A", duty=0.5, gain=0.21, bass_bounce=True, busy_shape=(0, 1), arp=True,
             counter={"semis": 9, "gain": 0.07, "duty": 0.5}),
        Slot("B", duty=0.5, gain=0.22, bass_bounce=True, arp=True,
             counter={"semis": 4, "gain": 0.08, "duty": 0.5}),
        Slot("A", duty=0.5, gain=0.22, bass_bounce=True, busy_shape=(0, 2), arp=True,
             counter={"semis": 4, "gain": 0.08, "duty": 0.5}),
        Slot("A", duty=0.5, gain=0.20, bass_bounce=True, busy_shape=(0, 1), ficta_=True),
    ]
    s = sized(bpm, form, swing=swing)
    lay_form(s, form, arp_gain=0.08, arp_duty=0.5)
    for bar in range(int(s.beats // 4)):
        base = bar * 4
        s.kick(base, 0.32)
        s.kick(base + 2, 0.28)
        ## HANDCLAPS: two snares a sixteenth apart on the backbeat. A room full
        ## of people does not clap in unison, and the flam is what sells it.
        for hit in (1, 3):
            s.snare(base + hit, 0.19, period=2)
            s.snare(base + hit + 0.0625, 0.13, period=3)
        for e in (0.5, 1.5, 2.5, 3.5):
            s.hat(base + e, 0.06)
        if bar % 8 == 7:
            for k in range(4):
                s.snare(base + 3.0 + k * 0.25, 0.09 + k * 0.03, period=2)
    return s


def fight(bpm=152):
    """AN ORDINARY LEAGUE BOUT, and the design constraint here is different from
    every other track: **it plays UNDER gameplay.**

    Everything else in this set accompanies a screen you are reading. This one
    accompanies a fight you are watching and giving orders in, for three rounds
    of up to two minutes each. So it is written to be the LEAST melodically
    prominent thing in the set — the lead sits well back, the rhythm section
    carries it, and the phrases repeat without ornament.

    That is also what keeps it from being cup night again. Cup night is a feature
    with the tune in front; this is a groove with the tune behind it. Same
    material, opposite balance."""
    form = [
        Slot("A", duty=0.25, gain=0.13, bass_sub=0.5, arp=True),
        Slot("A", duty=0.25, gain=0.13, bass_sub=0.5, arp=True),
        Slot("B", duty=0.25, gain=0.14, bass_sub=0.5, arp=True),
        Slot("A", duty=0.25, gain=0.13, bass_sub=0.5, arp=True),
        Slot("A", duty=0.25, gain=0.14, bass_sub=0.5, arp=True,
             counter={"semis": 7, "gain": 0.06, "duty": 0.5}),
        Slot("B", duty=0.25, gain=0.15, bass_sub=0.5, arp=True,
             counter={"semis": 7, "gain": 0.06, "duty": 0.5}),
        Slot("A", duty=0.25, gain=0.14, bass_sub=0.5, arp=True),
        Slot("A", duty=0.25, gain=0.13, bass_sub=0.5, arp=True),
    ]
    s = sized(bpm, form)
    ## Chords louder than the lead. That inversion IS the track.
    lay_form(s, form, arp_gain=0.125, arp_duty=0.34)
    for bar in range(int(s.beats // 4)):
        base = bar * 4
        s.kick(base, 0.32)
        s.kick(base + 1.5, 0.22)
        s.kick(base + 2, 0.28)
        s.war(base + 1, 0.22)
        s.war(base + 3, 0.24)
        s.snare(base + 1, 0.20)
        s.snare(base + 3, 0.20)
        for e in (0.5, 2.5):
            s.hat(base + e, 0.05)
    return s


TRACKS = {
    "menu": (menu, "Title screen. The tune stated plainly, call-and-response, a march."),
    "hosted": (hosted, "Your own tournament. The only track that swings — a party, not a fight."),
    "fight": (fight, "A league bout. A groove with the tune behind it, not in front."),
    "club": (club, "The clubhouse. Thin, busy, 25% duty — ignorable on purpose."),
    "cup": (cup, "Cup night. Same tune, faster, war drums arrive."),
    "final": (final, "The final. Its own song — D Phrygian riff, not the club theme."),
    "worlds": (worlds, "Worlds. The melody over a medieval drone — grand, not fast."),
    "champion": (champion, "Champion. The melody lifted out of Dorian into major."),
}


def check_voices_are_clean(limit=3.0):
    """A UNIT TEST OF THE VOICES, and the third attempt at measuring this.

    The two before it tried to score whole bars of finished music and both
    failed for the same reason: **they could not separate the good case from the
    known bad one.** Run across a mix, a sustained chord and a ringing arpeggio
    measured 8.0 % against 9.2 %, because a melody's note attacks smear the
    spectrum far more than the artefact does. Run on the harmony channel alone,
    the sparse clubhouse — the one track Pete never complained about — scored
    WORST of the four, because a melodic line of short notes always reads as
    inharmonic and a sustained chord does not.

    A measurement that ranks the good track worst is not evidence. So this stops
    scoring music and tests the VOICES, in isolation, where the difference is not
    subtle:

        held square, one note      0.4 - 1.0 %
        sustained power chord      0.1 - 0.6 %
        the same notes arpeggiated  37 - 55 %

    A hundred and fifty to one. That is the whole finding, and it is why the
    arpeggio is gone rather than tuned."""
    ok = True
    for label, notes in (("chord A/E", ["A2", "E3"]),
                         ("chord D/A", ["D3", "A3"]),
                         ("chord D/F#", ["D4", "F#4"]),
                         ("single D5", ["D5"])):
        s = Song(150, 4)
        s.chord(0, notes, 2.0, duty=0.5, gain=1.0)
        x = s.ch["p2"][:int(1.5 * SR)]
        X = np.abs(np.fft.rfft(x * np.hanning(len(x))))
        fr = np.fft.rfftfreq(len(x), 1.0 / SR)
        keep = fr > 60.0
        tot = float(np.sum(X[keep] ** 2)) or 1.0
        harm = np.zeros_like(fr, dtype=bool)
        for n in notes:
            f0 = hz(n)
            k = 1
            while f0 * k < SR / 2:
                harm |= np.abs(fr - f0 * k) < 16.0
                k += 1
        v = 100.0 * float(np.sum(X[keep & ~harm] ** 2)) / tot
        if v > limit:
            ok = False
        print("   voice %-11s inharmonic %5.2f%%  %s"
              % (label, v, "clean" if v <= limit else "RINGING"))
    return ok


def check_no_arpeggios_in_use(limit=0):
    """AND THAT NOTHING REACHES FOR THE RINGING VOICE AGAIN.

    `arp()` is kept — it is a correct implementation of a real technique and the
    comment on it is worth having — but nothing in the shipped arrangements may
    call it. A structural assertion rather than an acoustic one, because the
    acoustic one has already proved unable to see this in context."""
    import inspect
    used = 0
    for name, (fn, _) in TRACKS.items():
        src = inspect.getsource(fn)
        for line in src.split("\n"):
            code = line.split("##")[0]
            if ".arp(" in code or "arp=True" in code and False:
                used += 1
                print("   %s still calls arp(): %s" % (name, line.strip()))
    print("   arpeggio calls in shipped arrangements: %d  %s"
          % (used, "none" if used <= limit else "REGRESSION"))
    return used <= limit


def check_no_harsh_section(song, name, limit=1.8):
    """NO PART OF A TRACK MAY BE MUCH BRIGHTER THAN THE REST OF IT.

    The general form of the bug Pete kept hearing. The first cause was a
    synthesis defect (an oscillator reset laying a comb of spurious frequencies
    over everything); the second was a writing decision (the lead jumping an
    octave, which doubles every harmonic and pushes a square's energy into the
    band the ear reads as piercing). Both present as *one section sounding like a
    weapon while the rest is fine*, so that is what is measured: energy above
    5 kHz, bar by bar, against the track's own median.

    Against the track's own median rather than an absolute, because a square wave
    is inherently bright and the final is SUPPOSED to be brighter than the
    clubhouse. What is not allowed is a spike inside one track.

    THE NOISE CHANNEL IS EXCLUDED, for the same reason it is excluded from the
    inharmonic check: a drum is broadband by definition and a snare ROLL is the
    most broadband thing in the set. Measuring it flagged the final's bar 24 at
    10.6 % — which is a twelve-hit fill going into the breakdown, doing exactly
    what a fill is for. A check that fires on correct drumming is a check that
    gets ignored."""
    mono = song.ch["p1"] + song.ch["p2"] + song.ch["tri"]
    per = int(4 * song.spb * SR)
    vals, bars = [], int(song.beats // 4)
    for b in range(bars):
        seg = mono[b * per:(b + 1) * per]
        if len(seg) < 1024:
            continue
        X = np.abs(np.fft.rfft(seg * np.hanning(len(seg))))
        fr = np.fft.rfftfreq(len(seg), 1.0 / SR)
        t = float(np.sum(X ** 2)) or 1.0
        vals.append(100.0 * float(np.sum(X[fr > 5000] ** 2)) / t)
    med = float(np.median(vals))
    worst = max(vals)
    at = vals.index(worst) + 1
    ok = (worst - med) <= limit
    print("   %-9s brightness median %.2f%%, worst bar %.2f%% (bar %d)  %s"
          % (name, med, worst, at, "ok" if ok else "HARSH SECTION"))
    return ok


def check_register(name, fn, ceiling="C6", max_high_share=0.07):
    """HOW MUCH OF THIS TRACK LIVES UP WHERE IT HURTS?

    Read off the SCORE by intercepting every note the arrangement writes, not
    inferred from a spectrum — the first attempt at this measured "highest strong
    partial" and was reading a square wave's third HARMONIC, which put the menu
    and the clubhouse within a few hertz of each other and explained nothing.

    Two things are asserted: nothing above the ceiling at all, and no more than
    a small share of notes above A5. The share matters as much as the peak — a
    single high note is a highlight, and thirty-four of them is a register."""
    notes = []
    orig = Song.lead

    def spy(self, beat, note, beats, duty=0.5, gain=0.22, vib=False, chan="p1"):
        if note:
            notes.append((note, hz(note)))
        return orig(self, beat, note, beats, duty, gain, vib, chan)

    Song.lead = spy
    try:
        fn()
    finally:
        Song.lead = orig

    top = hz(ceiling)
    over = [n for n, f in notes if f > top + 0.5]
    high = [n for n, f in notes if f > hz("A5") + 0.5]
    share = len(high) / float(max(1, len(notes)))
    ok = not over and share <= max_high_share
    print("   %-9s register: %d notes, %d above A5 (%.0f%%), %d above %s  %s"
          % (name, len(notes), len(high), 100 * share, len(over), ceiling,
             "ok" if ok else "TOO HIGH"))
    return ok


def _fingerprint(name, fn):
    """Everything about an arrangement that the ear uses to tell it from its
    neighbor, read off the SCORE — the tune, the kit, the bass, the balance."""
    lead, bassn, drums = [], [], []
    ol, ob, ok_, osn, oh = Song.lead, Song.bass, Song.kick, Song.snare, Song.hat

    def sl(self, beat, note, beats, duty=0.5, gain=0.22, vib=False, chan="p1"):
        if note:
            lead.append((beat, note, beats, duty, chan))
        return ol(self, beat, note, beats, duty, gain, vib, chan)

    def sb(self, beat, note, beats, gain=0.30):
        if note:
            bassn.append((beat, note))
        return ob(self, beat, note, beats, gain)

    def mk(orig, tag):
        def spy(self, beat, *a, **k):
            drums.append((tag, beat))
            return orig(self, beat, *a, **k)
        return spy

    Song.lead, Song.bass = sl, sb
    Song.kick, Song.snare, Song.hat = mk(ok_, "k"), mk(osn, "s"), mk(oh, "h")
    try:
        song = fn()
    finally:
        Song.lead, Song.bass = ol, ob
        Song.kick, Song.snare, Song.hat = ok_, osn, oh

    dur = song.beats * song.spb
    tune = [x for x in lead if x[4] == "p1"]

    pcs = np.zeros(12)
    for (_, n, _, _, _) in lead:
        pcs[NOTE_PC[n[:-1]]] += 1

    iv = np.zeros(25)
    seq = [hz(n) for (_, n, _, _, _) in sorted(tune)]
    for a, b in zip(seq, seq[1:]):
        iv[int(np.clip(round(12 * np.log2(b / a)) + 12, 0, 24))] += 1

    dh = {}
    for (_, _, _, d, _) in lead:
        dh[round(d, 3)] = dh.get(round(d, 3), 0) + 1
    tot = float(max(1, sum(dh.values())))

    grid = {}
    for tag, beat in drums:
        g = grid.setdefault(tag, np.zeros(16))
        g[int(round((beat % 4) * 4)) % 16] += 1

    bn = [n for (_, n) in sorted(bassn)]
    octjump = sum(1 for a, b in zip(bn, bn[1:])
                  if a[:-1] == b[:-1] and a != b) / float(max(1, len(bn)))
    r1 = float(np.sqrt(np.mean(song.ch["p1"] ** 2)))
    r2 = float(np.sqrt(np.mean(song.ch["p2"] ** 2)))
    return dict(
        name=name, bpm=song.bpm, swing=song.swing,
        dens=len(tune) / dur,
        pcs=pcs / max(1.0, pcs.sum()),
        iv=iv / max(1.0, iv.sum()),
        duty={k: v / tot for k, v in dh.items()},
        grid={k: v / max(1.0, v.sum()) for k, v in grid.items()},
        octjump=octjump,
        prom=r1 / max(1e-9, r2),
        sustain=sum(ln for (_, _, ln, _, _) in tune if ln >= 1.5) / max(1.0, song.beats),
    )


## HOW CLOSE TWO ARRANGEMENTS MAY BE.
##
## Calibrated, not guessed. `_twin_controls()` below renders the clubhouse at a
## different tempo and nothing else — which is the literal failure mode, "the
## same arrangement with a different tempo marking" — and that scores 0.95. The
## real set tops out at 0.81. The gate sits between them, and the build asserts
## BOTH ends every time: if the manufactured twin ever stops scoring above the
## gate, the metric has gone blind and the check says so instead of going green.
TWIN_GATE = 0.88

_TWIN_W = dict(melody=1.6, drums=1.4, dens=1.2, prom=1.2, mode=1.0, duty=1.0,
               tempo=1.0, bass=1.0, sustain=1.0, swing=1.0)


def _cos(a, b):
    d = float(np.linalg.norm(a) * np.linalg.norm(b))
    return float(a @ b / d) if d else 0.0


def _twin_score(a, b):
    ks = set(a["grid"]) | set(b["grid"])
    z = np.zeros(16)
    drums = float(np.mean([_cos(a["grid"].get(k, z), b["grid"].get(k, z))
                           for k in ks])) if ks else 0.0
    dk = set(a["duty"]) | set(b["duty"])
    parts = dict(
        melody=_cos(a["iv"], b["iv"]),
        mode=_cos(a["pcs"], b["pcs"]),
        drums=drums,
        duty=sum(min(a["duty"].get(k, 0.0), b["duty"].get(k, 0.0)) for k in dk),
        tempo=1.0 - min(1.0, abs(a["bpm"] - b["bpm"]) / 40.0),
        dens=1.0 - min(1.0, abs(a["dens"] - b["dens"]) / 3.0),
        bass=1.0 - min(1.0, abs(a["octjump"] - b["octjump"])),
        prom=1.0 - min(1.0, abs(np.log2(max(a["prom"], 1e-6))
                                - np.log2(max(b["prom"], 1e-6))) / 2.5),
        sustain=1.0 - min(1.0, abs(a["sustain"] - b["sustain"]) / 0.5),
        swing=1.0 - min(1.0, abs(a["swing"] - b["swing"]) / 0.08),
    )
    return sum(_TWIN_W[k] * parts[k] for k in _TWIN_W) / sum(_TWIN_W.values()), parts


def check_no_two_tracks_are_twins(gate=TWIN_GATE):
    """NO TWO TRACKS MAY BE THE SAME ARRANGEMENT AT DIFFERENT TEMPOS.

    Three times now the same failure: the final was cup night sped up, the menu
    borrowed Worlds' drone, and then the menu, the clubhouse and your own
    tournament came out as ONE arrangement at 118 / 124 / 132 — measuring 0.92,
    0.97 and 0.90 against each other. Every time, Pete heard it and no check
    did, because every check in this file looks at ONE track.

    The register already had the rule written down — *a signature belongs to one
    track* — and a rule in a document is not a gate. This is the gate.

    It reads the score, not the audio, and it prints the whole matrix every
    build so a pair drifting together is visible before it is audible."""
    names = list(TRACKS.keys())
    F = {n: _fingerprint(n, TRACKS[n][0]) for n in names}

    worst, pairs = 0.0, []
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            v, parts = _twin_score(F[a], F[b])
            pairs.append((v, a, b, parts))
            worst = max(worst, v)
    pairs.sort(reverse=True, key=lambda x: x[0])

    ## THE POSITIVE CONTROL. A check that cannot separate the good case from the
    ## known bad case is not evidence — so the bad case is manufactured here,
    ## every run, rather than assumed.
    twin, _ = _twin_score(F["club"], _fingerprint("club'", lambda: club(bpm=132)))
    blind = twin <= gate

    over = [p for p in pairs if p[0] > gate]
    ok = not over and not blind

    print("   twins     worst pair %s/%s %.2f (gate %.2f), control twin %.2f  %s"
          % (pairs[0][1], pairs[0][2], pairs[0][0], gate, twin,
             "BLIND — the control twin scored under the gate" if blind
             else ("ok" if ok else "TOO ALIKE")))
    for v, a, b, parts in pairs[:3]:
        print("             %-9s %-9s %.2f  " % (a, b, v)
              + " ".join("%s %.2f" % (k, parts[k]) for k in
                         ("melody", "drums", "duty", "dens", "bass", "prom", "swing")))
    for v, a, b, _ in over:
        print("             TOO ALIKE: %s and %s at %.2f" % (a, b, v))
    return ok


def check_holes(song, name, max_quiet_bars=1):
    """NO BAR OF A TRACK MAY BE DRUMS ONLY.

    This is the check that would have caught the thing Pete heard. It measures
    tonal energy — both pulses plus the triangle — bar by bar, and fails on any
    run of bars with none. `max_quiet_bars` is 1 because a single bar of drums is
    a fill and twenty-four of them is a bug."""
    per = int(4 * song.spb * SR)
    bars = int(song.beats // 4)
    tonal = np.abs(song.ch["p1"]) + np.abs(song.ch["p2"]) + np.abs(song.ch["tri"])
    quiet, worst, run = [], 0, 0
    for b in range(bars):
        seg = tonal[b * per:(b + 1) * per]
        if len(seg) == 0 or float(np.max(seg)) < 1e-3:
            quiet.append(b + 1)
            run += 1
            worst = max(worst, run)
        else:
            run = 0
    ok = worst <= max_quiet_bars
    print("   %-9s %2d bars, %d with no tune (longest run %d)  %s"
          % (name, bars, len(quiet), worst, "ok" if ok else "HOLE: bars " + str(quiet)))
    return ok


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "/tmp/music"
    os.makedirs(out, exist_ok=True)
    only = sys.argv[2] if len(sys.argv) > 2 else None
    good = check_voices_are_clean() and check_no_arpeggios_in_use()
    if not only:
        good = check_no_two_tracks_are_twins() and good
    for name, (fn, about) in TRACKS.items():
        if only and name != only:
            continue
        song = fn()
        good = check_register(name, fn) and good
        good = check_holes(song, name) and good
        good = check_no_harsh_section(song, name) and good
        mono = song.mix(loop=(name != "champion"))
        write_wav(os.path.join(out, name + "_raw.wav"), mono)
        print("%-9s %5.1f s  %s" % (name, len(mono) / SR, about))
    if not good:
        print("\nNOT FIT TO SHIP — a track has a hole in it, or the synth is buzzing.")
        sys.exit(1)
